'goblinState after' {}
'goblin' {} <ref *1> Player {
  _events: [Object: null prototype] { write: [Function (anonymous)] },
  _eventsCount: 1,
  _maxListeners: undefined,
  location: 'home',
  game: <ref *2> Game {
    _events: [Object: null prototype] { all: [Function (anonymous)] },
    _eventsCount: 1,
    _maxListeners: undefined,
    rooms: {
      mall: [Room],
      'The Cellar': [Room],
      beach: [Room],
      beachbar: [Room],
      home: [Room],
      home2: [Room],
      moon_0_0: [Room],
      moon_1_0: [Room],
      moon_2_0: [Room],
      moon_3_0: [Room],
      moon_4_0: [Room],
      moon_0_1: [Room],
      moon_1_1: [Room],
      moon_2_1: [Room],
      moon_3_1: [Room],
      moon_4_1: [Room],
      moon_0_2: [Room],
      moon_1_2: [Room],
      moon_2_2: [Room],
      moon_3_2: [Room],
      moon_4_2: [Room],
      moon_0_3: [Room],
      moon_1_3: [Room],
      moon_2_3: [Room],
      moon_3_3: [Room],
      moon_4_3: [Room],
      moon_0_4: [Room],
      moon_1_4: [Room],
      moon_2_4: [Room],
      moon_3_4: [Room],
      moon_4_4: [Room],
      olly: [Room],
      'broom cupboard': [Room],
      'First Jedi Temple': [Room],
      'Middle Street': [Room],
      'The Hop Poles': [Room],
      'Beer Garden': [Room],
      "susanna's happy place": [Room],
      tradingFloor: [Room],
      votingBooth: [Room]
    },
    players: {
      darthatthemall: [Player],
      bartender: [Player],
      'the beer goblin': [Player],
      rover0: [Player],
      rover1: [Player],
      rover2: [Player],
      rover3: [Player],
      rover4: [Player],
      rover5: [Player],
      parrot: [Player],
      'town crier': [Player],
      tom: [Circular *1]
    },
    commands: {
      godmother: [Function],
      clickheels: [Function],
      commands: [Function],
      help: [Function],
      get: [Function],
      take: [Function],
      drop: [Function],
      inventory: [Function],
      use: [Function],
      go: [Function],
      n: [Function],
      s: [Function],
      e: [Function],
      w: [Function],
      u: [Function],
      d: [Function],
      exits: [Function],
      teleport: [Function],
      say: [Function],
      shout: [Function],
      list: [Function],
      look: [Function],
      see: [Function],
      iam: [Function],
      whoami: [Function],
      who: [Function],
      tell: [Function],
      'climb ladder': [Function],
      'sit chair': [Function],
      'tuckin chair': [Function],
      check: [Function],
      'delete-room': [Function],
      emote: [Function],
      find: [Function],
      ls: [Function],
      'read compass': [Function],
      'map compass': [Function],
      'eat banna': [Function],
      'roll dice': [Function],
      'read map': [Function],
      'use map': [Function],
      'drink Beer': [Function],
      'poke remi': [Function],
      killallremis: [Function],
      'press redbutton': [Function],
      'rake zen_garden': [Function],
      where: [Function],
      vote: [Function]
    },
    display: Display { object: [Circular *2], broadcast: [Function: broadcast] },
    _loadingModule: null,
    _allowDefault: true,
    goblinState: {},
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  name: 'tom',
  inventory: [],
  display: Display { object: [Circular *1], broadcast: [Function: write] },
  [Symbol(shapeMode)]: false,
  [Symbol(kCapture)]: false
} 'tell me about the skiff?'
'goblinState after' undefined
'goblin' 0 <ref *1> Player {
  _events: [Object: null prototype] { write: [Function (anonymous)] },
  _eventsCount: 1,
  _maxListeners: undefined,
  location: 'The Cellar',
  game: <ref *2> Game {
    _events: [Object: null prototype] { all: [Function (anonymous)] },
    _eventsCount: 1,
    _maxListeners: undefined,
    rooms: {
      mall: [Room],
      'The Cellar': [Room],
      beach: [Room],
      beachbar: [Room],
      home: [Room],
      home2: [Room],
      moon_0_0: [Room],
      moon_1_0: [Room],
      moon_2_0: [Room],
      moon_3_0: [Room],
      moon_4_0: [Room],
      moon_0_1: [Room],
      moon_1_1: [Room],
      moon_2_1: [Room],
      moon_3_1: [Room],
      moon_4_1: [Room],
      moon_0_2: [Room],
      moon_1_2: [Room],
      moon_2_2: [Room],
      moon_3_2: [Room],
      moon_4_2: [Room],
      moon_0_3: [Room],
      moon_1_3: [Room],
      moon_2_3: [Room],
      moon_3_3: [Room],
      moon_4_3: [Room],
      moon_0_4: [Room],
      moon_1_4: [Room],
      moon_2_4: [Room],
      moon_3_4: [Room],
      moon_4_4: [Room],
      olly: [Room],
      'broom cupboard': [Room],
      'First Jedi Temple': [Room],
      'Middle Street': [Room],
      'The Hop Poles': [Room],
      'Beer Garden': [Room],
      "susanna's happy place": [Room],
      tradingFloor: [Room],
      votingBooth: [Room]
    },
    players: {
      darthatthemall: [Player],
      bartender: [Player],
      'the beer goblin': [Player],
      rover0: [Player],
      rover1: [Player],
      rover2: [Player],
      rover3: [Player],
      rover4: [Player],
      rover5: [Player],
      parrot: [Player],
      'town crier': [Player],
      tom: [Circular *1]
    },
    commands: {
      godmother: [Function],
      clickheels: [Function],
      commands: [Function],
      help: [Function],
      get: [Function],
      take: [Function],
      drop: [Function],
      inventory: [Function],
      use: [Function],
      go: [Function],
      n: [Function],
      s: [Function],
      e: [Function],
      w: [Function],
      u: [Function],
      d: [Function],
      exits: [Function],
      teleport: [Function],
      say: [Function],
      shout: [Function],
      list: [Function],
      look: [Function],
      see: [Function],
      iam: [Function],
      whoami: [Function],
      who: [Function],
      tell: [Function],
      'climb ladder': [Function],
      'sit chair': [Function],
      'tuckin chair': [Function],
      check: [Function],
      'delete-room': [Function],
      emote: [Function],
      find: [Function],
      ls: [Function],
      'read compass': [Function],
      'map compass': [Function],
      'eat banna': [Function],
      'roll dice': [Function],
      'read map': [Function],
      'use map': [Function],
      'drink Beer': [Function],
      'poke remi': [Function],
      killallremis: [Function],
      'press redbutton': [Function],
      'rake zen_garden': [Function],
      where: [Function],
      vote: [Function]
    },
    display: Display { object: [Circular *2], broadcast: [Function: broadcast] },
    _loadingModule: null,
    _allowDefault: true,
    goblinState: {},
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  name: 'tom',
  inventory: [],
  display: Display { object: [Circular *1], broadcast: [Function: write] },
  lastSay: 1771956249758,
  [Symbol(shapeMode)]: false,
  [Symbol(kCapture)]: false
} undefined
'goblinState after' { tom: 1 }
'goblin' { tom: 1 } <ref *1> Player {
  _events: [Object: null prototype] { write: [Function (anonymous)] },
  _eventsCount: 1,
  _maxListeners: undefined,
  location: 'Beer Garden',
  game: <ref *2> Game {
    _events: [Object: null prototype] { all: [Function (anonymous)] },
    _eventsCount: 1,
    _maxListeners: undefined,
    rooms: {
      mall: [Room],
      'The Cellar': [Room],
      beach: [Room],
      beachbar: [Room],
      home: [Room],
      home2: [Room],
      moon_0_0: [Room],
      moon_1_0: [Room],
      moon_2_0: [Room],
      moon_3_0: [Room],
      moon_4_0: [Room],
      moon_0_1: [Room],
      moon_1_1: [Room],
      moon_2_1: [Room],
      moon_3_1: [Room],
      moon_4_1: [Room],
      moon_0_2: [Room],
      moon_1_2: [Room],
      moon_2_2: [Room],
      moon_3_2: [Room],
      moon_4_2: [Room],
      moon_0_3: [Room],
      moon_1_3: [Room],
      moon_2_3: [Room],
      moon_3_3: [Room],
      moon_4_3: [Room],
      moon_0_4: [Room],
      moon_1_4: [Room],
      moon_2_4: [Room],
      moon_3_4: [Room],
      moon_4_4: [Room],
      olly: [Room],
      'broom cupboard': [Room],
      'First Jedi Temple': [Room],
      'Middle Street': [Room],
      'The Hop Poles': [Room],
      'Beer Garden': [Room],
      "susanna's happy place": [Room],
      tradingFloor: [Room],
      votingBooth: [Room]
    },
    players: {
      darthatthemall: [Player],
      bartender: [Player],
      'the beer goblin': [Player],
      rover0: [Player],
      rover1: [Player],
      rover2: [Player],
      rover3: [Player],
      rover4: [Player],
      rover5: [Player],
      parrot: [Player],
      'town crier': [Player],
      tom: [Circular *1]
    },
    commands: {
      godmother: [Function],
      clickheels: [Function],
      commands: [Function],
      help: [Function],
      get: [Function],
      take: [Function],
      drop: [Function],
      inventory: [Function],
      use: [Function],
      go: [Function],
      n: [Function],
      s: [Function],
      e: [Function],
      w: [Function],
      u: [Function],
      d: [Function],
      exits: [Function],
      teleport: [Function],
      say: [Function],
      shout: [Function],
      list: [Function],
      look: [Function],
      see: [Function],
      iam: [Function],
      whoami: [Function],
      who: [Function],
      tell: [Function],
      'climb ladder': [Function],
      'sit chair': [Function],
      'tuckin chair': [Function],
      check: [Function],
      'delete-room': [Function],
      emote: [Function],
      find: [Function],
      ls: [Function],
      'read compass': [Function],
      'map compass': [Function],
      'eat banna': [Function],
      'roll dice': [Function],
      'read map': [Function],
      'use map': [Function],
      'drink Beer': [Function],
      'poke remi': [Function],
      killallremis: [Function],
      'press redbutton': [Function],
      'rake zen_garden': [Function],
      where: [Function],
      vote: [Function]
    },
    display: Display { object: [Circular *2], broadcast: [Function: broadcast] },
    _loadingModule: null,
    _allowDefault: true,
    goblinState: { tom: 1 },
    [Symbol(shapeMode)]: false,
    [Symbol(kCapture)]: false
  },
  name: 'tom',
  inventory: [],
  display: Display { object: [Circular *1], broadcast: [Function: write] },
  lastSay: 1771956249758,
  [Symbol(shapeMode)]: false,
  [Symbol(kCapture)]: false
} 'hi remi'
'goblinState after' undefined
